var name = "Sujeet kumar";
var school = "DAV public school";
var grade ="A";
var section="A";
var rollno= "11";
var maths ="97";
var Physics ="93";
var chemistery="100";
console.log("*************************************************************************************");
console.log("                                STUDENT REPORT CARD                      ");
console.log("**************************************************************************************");
console.log("Name: "+ name);
console.log("School: "+ school);
console.log("grade: "+ grade);
console.log("section: "+ section);
console.log("rollno: "+ rollno);
console.log("------------------------------------------------------------");
console.log("Subjects"   + " | " + "Marks" );
console.log("maths"      + " | " + "97");
console.log("physics"    + " | " + "93");
console.log("chemistery" + " | " + "100");
console.log("-----------------------------------------------------------");
